<?php


/**
 * This class defines the structure of the 'participante' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/26/14 04:34:27
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ParticipanteTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ParticipanteTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('participante');
		$this->setPhpName('Participante');
		$this->setClassname('Participante');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('PAR_CODIGO', 'ParCodigo', 'INTEGER', true, 11, null);
		$this->addColumn('PAR_PERS_CODIGO', 'ParPersCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PAR_PRO_CODIGO', 'ParProCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PAR_USU_CODIGO', 'ParUsuCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PAR_FECHA_REGISTRO', 'ParFechaRegistro', 'TIMESTAMP', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ParticipanteTableMap
