<?php


/**
 * This class defines the structure of the 'presupuesto' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/06/14 03:51:53
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class PresupuestoTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.PresupuestoTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('presupuesto');
		$this->setPhpName('Presupuesto');
		$this->setClassname('Presupuesto');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('PRE_CODIGO', 'PreCodigo', 'INTEGER', true, 11, null);
		$this->addColumn('PRE_VALOR', 'PreValor', 'DOUBLE', false, null, null);
		$this->addColumn('PRE_FECHA_REGISTRO', 'PreFechaRegistro', 'TIMESTAMP', false, null, null);
		$this->addColumn('PRE_ELIMINADO', 'PreEliminado', 'SMALLINT', false, 6, null);
		$this->addColumn('PRE_TIPP_CODIGO', 'PreTippCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PRE_USU_CODIGO', 'PreUsuCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PRE_PRO_CODIGO', 'PreProCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PRE_DESCRIPCION', 'PreDescripcion', 'VARCHAR', false, 200, null);
		$this->addColumn('PRE_CON_CODIGO', 'PreConCodigo', 'INTEGER', false, 11, null);
		$this->addColumn('PRE_FECHA', 'PreFecha', 'DATE', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // PresupuestoTableMap
