<?php


/**
 * This class defines the structure of the 'registro_rep_maquina' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 08/28/13 00:53:32
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class RegistroRepMaquinaTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.RegistroRepMaquinaTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('registro_rep_maquina');
		$this->setPhpName('RegistroRepMaquina');
		$this->setClassname('RegistroRepMaquina');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('RRM_CODIGO', 'RrmCodigo', 'INTEGER', true, 11, null);
		$this->addForeignKey('RRM_MAQ_CODIGO', 'RrmMaqCodigo', 'INTEGER', 'maquina', 'MAQ_CODIGO', false, 11, null);
		$this->addForeignKey('RRM_REP_CODIGO', 'RrmRepCodigo', 'INTEGER', 'repuesto', 'REP_CODIGO', false, 11, null);
		$this->addColumn('RRM_CONSUMO', 'RrmConsumo', 'INTEGER', false, 11, null);
		$this->addColumn('RRM_FECHA_CAMBIO', 'RrmFechaCambio', 'DATE', false, null, null);
		$this->addColumn('RRM_FECHA_PROX_CAMBIO', 'RrmFechaProxCambio', 'DATE', false, null, null);
		$this->addColumn('RRM_OBSERVACIONES', 'RrmObservaciones', 'VARCHAR', false, 300, null);
		$this->addForeignKey('RRM_USU_REGISTRA', 'RrmUsuRegistra', 'INTEGER', 'usuario', 'USU_CODIGO', false, 11, null);
		$this->addColumn('RRM_FECHA_REGISTRO', 'RrmFechaRegistro', 'DATE', false, null, null);
		$this->addForeignKey('RRM_USU_ACTUALIZA', 'RrmUsuActualiza', 'INTEGER', 'usuario', 'USU_CODIGO', false, 11, null);
		$this->addColumn('RRM_FECHA_ACTUALIZACION', 'RrmFechaActualizacion', 'DATE', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Maquina', 'Maquina', RelationMap::MANY_TO_ONE, array('rrm_maq_codigo' => 'maq_codigo', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('Repuesto', 'Repuesto', RelationMap::MANY_TO_ONE, array('rrm_rep_codigo' => 'rep_codigo', ), 'SET NULL', 'SET NULL');
    $this->addRelation('UsuarioRelatedByRrmUsuRegistra', 'Usuario', RelationMap::MANY_TO_ONE, array('rrm_usu_registra' => 'usu_codigo', ), 'RESTRICT', 'RESTRICT');
    $this->addRelation('UsuarioRelatedByRrmUsuActualiza', 'Usuario', RelationMap::MANY_TO_ONE, array('rrm_usu_actualiza' => 'usu_codigo', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // RegistroRepMaquinaTableMap
