CREATE DATABASE indicadorescompras;
DROP TABLE ahorrosterminodepago;
DROP TABLE asignaciondepedidos;
DROP TABLE codigoscreados;
DROP TABLE codigostiempo;
DROP TABLE coface;
DROP TABLE convenio;
DROP TABLE conversacion;
DROP TABLE cumplimientodeentrega;
DROP TABLE metas;
DROP TABLE pedidosabiertos;
DROP TABLE plancarrera;
DROP TABLE plansucesion;
DROP TABLE solpeds;
DROP TABLE srm;
DROP TABLE terminosdepago;
DROP TABLE contratos;
DROP TABLE creaciondeproveedores;
DROP TABLE ahorros;
DROP TABLE usuario;
CREATE TABLE usuario (id INT NOT NULL IDENTITY, nombre VARCHAR(50) NOT NULL, contrasena VARCHAR(50) NOT NULL, nombres VARCHAR(50) NOT NULL, apellidos VARCHAR(50) NOT NULL, tipo VARCHAR(40) NOT NULL, correo VARCHAR(50) NOT NULL, ficha VARCHAR(50) NOT NULL, cargo VARCHAR(50) NOT NULL, meta VARCHAR(50) NOT NULL, PRIMARY KEY (id));
CREATE TABLE ahorros (id INT NOT NULL IDENTITY, pedido VARCHAR(50) NOT NULL, tipo VARCHAR(50) NOT NULL, grupo VARCHAR(50) NOT NULL, nit VARCHAR(50) NOT NULL, razon VARCHAR(50) NOT NULL, fechainicio DATE NOT NULL, fechafin DATE NOT NULL, presupuesto VARCHAR(50) NOT NULL, preciohistorico VARCHAR(50) NOT NULL, preciomejor VARCHAR(50) NOT NULL, precioadjudicado VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE ahorrosterminodepago (id INT NOT NULL IDENTITY, pedido VARCHAR(50) NOT NULL, tipo VARCHAR(50) NOT NULL, grupo VARCHAR(50) NOT NULL, nit VARCHAR(50) NOT NULL, razon VARCHAR(50) NOT NULL, fechainicio DATE NOT NULL, fechafin DATE NOT NULL, pagoactual VARCHAR(50) NOT NULL, pagonegociada VARCHAR(50) NOT NULL, valor VARCHAR(50) NOT NULL, costodeoportunidad VARCHAR(20) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE asignaciondepedidos (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, tipo VARCHAR(20) NOT NULL, totalsolpeds VARCHAR(50) NOT NULL, solpedsmayor VARCHAR(50) NOT NULL, solpedsmenor VARCHAR(50) NOT NULL, dias VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE codigoscreados (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, solicitados VARCHAR(50) NOT NULL, creados VARCHAR(50) NOT NULL);
CREATE TABLE codigostiempo (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, codigos VARCHAR(50) NOT NULL, cumplimiento VARCHAR(50) NOT NULL);
CREATE TABLE coface (id INT NOT NULL IDENTITY, nit VARCHAR(50) NOT NULL, nombre VARCHAR(50) NOT NULL, grupo VARCHAR(50) NOT NULL, tipo VARCHAR(30) NOT NULL, calificacion VARCHAR(50) NOT NULL, aspectos VARCHAR(50) NOT NULL);
CREATE TABLE convenio (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, grupo VARCHAR(50) NOT NULL, porcentaje VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE conversacion (id INT NOT NULL IDENTITY, fecha DATE NOT NULL, tema VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE cumplimientodeentrega (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, tipo VARCHAR(20) NOT NULL, total VARCHAR(50) NOT NULL, pedidoscumplidos VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE metas (id INT NOT NULL IDENTITY, indicador VARCHAR(50) NOT NULL, meta VARCHAR(50) NOT NULL, valorreal VARCHAR(50) NOT NULL, condicion VARCHAR(30) NOT NULL);
CREATE TABLE pedidosabiertos (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, totalpedidos VARCHAR(50) NOT NULL, pedidosabiertos VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE plancarrera (id INT NOT NULL IDENTITY, nombre VARCHAR(50) NOT NULL, lugar VARCHAR(50) NOT NULL, fechainicio DATE NOT NULL, duracion VARCHAR(30) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE plansucesion (id INT NOT NULL IDENTITY, plansucesion VARCHAR(100) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE solpeds (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, totalsolpeds VARCHAR(50) NOT NULL, solpedsabiertas VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE srm (id INT NOT NULL IDENTITY, nit VARCHAR(50) NOT NULL, nombre VARCHAR(50) NOT NULL, grupo VARCHAR(50) NOT NULL, avance VARCHAR(20) NOT NULL, fecharegistro DATE NOT NULL);
CREATE TABLE terminosdepago (id INT NOT NULL IDENTITY, mes VARCHAR(20) NOT NULL, ano VARCHAR(50) NOT NULL, promedio VARCHAR(50) NOT NULL, usuario_id INT NOT NULL, PRIMARY KEY (id), FOREIGN KEY (usuario_id) REFERENCES usuario(id));
CREATE TABLE contratos (id INT NOT NULL IDENTITY, fechaingreso VARCHAR(50) NOT NULL, numerocontrato VARCHAR(50) NOT NULL, estado VARCHAR(40) NOT NULL, area VARCHAR(40) NOT NULL, comprador VARCHAR(60) NOT NULL, fechaentregajuridico VARCHAR(50) NOT NULL, fecharecibojuridico VARCHAR(50) NOT NULL, fechaentregafirma VARCHAR(50) NOT NULL, fechafinalizacion VARCHAR(50) NOT NULL, PRIMARY KEY (id));
CREATE TABLE creaciondeproveedores (id INT NOT NULL IDENTITY, fechareciboinformacion VARCHAR(50) NOT NULL, nit VARCHAR(50) NOT NULL, proveedor VARCHAR(60) NOT NULL, estado VARCHAR(60) NOT NULL, area VARCHAR(60) NOT NULL, comprador VARCHAR(60) NOT NULL, fechaenviogerentecompras VARCHAR(50) NOT NULL, fechaaprobaciongerentecompras VARCHAR(50) NOT NULL, fechasolicitudcreacion VARCHAR(50) NOT NULL, fechaimpuestos VARCHAR(50) NOT NULL, fechaenviocuentasporpagar VARCHAR(50) NOT NULL, fechacreacion VARCHAR(50) NOT NULL, PRIMARY KEY (id));
INSERT INTO usuario (nombre, contrasena, nombres, apellidos, tipo, correo, ficha, cargo, meta) VALUES ('dkcundar', 'zsTe2+WXoJKl', 'Diana', 'Cundar', 'Administrador de Proveedores', 'negra-1105@hotmail.com', '403846', 'Analista de Servicio de Proveedores', 0);