<?php


/**
 * Skeleton subclass for representing a row from the 'empleado' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 12/20/10 21:56:13
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Empleado extends BaseEmpleado {
	public function getNombreCompleto() {
		return $this->getEmplNombres().' '.$this->getEmplApellidos();
	}
} // Empleado
