<?php


/**
 * Skeleton subclass for performing query and update operations on the 'evento_por_categoria' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/05/11 22:58:11
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class EventoPorCategoriaPeer extends BaseEventoPorCategoriaPeer {

} // EventoPorCategoriaPeer
