<?php


/**
 * Skeleton subclass for performing query and update operations on the 'proyecto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/26/14 18:03:51
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class ProyectoPeer extends BaseProyectoPeer {

} // ProyectoPeer
