propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  alarma:
    _attributes: { phpName: Alarma }
    ala_codigo: { phpName: AlaCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    ala_concepto: { phpName: AlaConcepto, type: VARCHAR, size: '200', required: false }
    ala_con_codigo: { phpName: AlaConCodigo, type: VARCHAR, size: '200', required: false }
    ala_descripcion: { phpName: AlaDescripcion, type: VARCHAR, size: '500', required: false }
    ala_enviado: { phpName: AlaEnviado, type: SMALLINT, size: '6', required: false }
  asignaciondetiempo:
    _attributes: { phpName: Asignaciondetiempo }
    adt_codigo: { phpName: AdtCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    adt_mes: { phpName: AdtMes, type: VARCHAR, size: '100', required: false }
    adt_ano: { phpName: AdtAno, type: VARCHAR, size: '100', required: false }
    adt_asignacion: { phpName: AdtAsignacion, type: DOUBLE, required: false }
    adt_pers_codigo: { phpName: AdtPersCodigo, type: INTEGER, size: '11', required: false }
    adt_pro_codigo: { phpName: AdtProCodigo, type: INTEGER, size: '11', required: false }
    adt_pers_reg_codigo: { phpName: AdtPersRegCodigo, type: INTEGER, size: '11', required: false }
    adt_fecha_registro: { phpName: AdtFechaRegistro, type: TIMESTAMP, required: false }
    _indexes: { FK_reference_1: [adt_pers_codigo], FK_reference_2: [adt_pro_codigo], FK_reference_3: [adt_pers_reg_codigo] }
  concepto:
    _attributes: { phpName: Concepto }
    con_codigo: { phpName: ConCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    con_nombre: { phpName: ConNombre, type: VARCHAR, size: '30', required: false }
    con_fecha_registro: { phpName: ConFechaRegistro, type: TIMESTAMP, required: false }
    con_usu_codigo: { phpName: ConUsuCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_1: [con_usu_codigo] }
  conceptosingreso:
    _attributes: { phpName: Conceptosingreso }
    csi_codigo: { phpName: CsiCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    csi_valor: { phpName: CsiValor, type: DOUBLE, required: false }
    csi_fecha: { phpName: CsiFecha, type: DATE, required: false }
    csi_usu_codigo: { phpName: CsiUsuCodigo, type: INTEGER, size: '11', required: false }
    csi_con_codigo: { phpName: CsiConCodigo, type: INTEGER, size: '11', required: false }
    csi_ing_codigo: { phpName: CsiIngCodigo, type: INTEGER, size: '11', required: false }
    csi_pro_codigo: { phpName: CsiProCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_1: [csi_usu_codigo], FK_reference_2: [csi_con_codigo], FK_reference_3: [csi_ing_codigo], FK_reference_4: [csi_pro_codigo] }
  documento:
    _attributes: { phpName: Documento }
    doc_codigo: { phpName: DocCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    doc_documento_url: { phpName: DocDocumentoUrl, type: VARCHAR, size: '300', required: false }
    doc_fecha_registro: { phpName: DocFechaRegistro, type: TIMESTAMP, required: false }
    doc_eliminado: { phpName: DocEliminado, type: SMALLINT, size: '6', required: false }
    doc_tipd_codigo: { phpName: DocTipdCodigo, type: INTEGER, size: '11', required: false }
    doc_usu_codigo: { phpName: DocUsuCodigo, type: INTEGER, size: '11', required: false }
    doc_pro_codigo: { phpName: DocProCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_1: [doc_tipd_codigo], FK_reference_2: [doc_usu_codigo], FK_reference_3: [doc_pro_codigo] }
  egreso:
    _attributes: { phpName: Egreso }
    egr_codigo: { phpName: EgrCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    egr_con_codigo: { phpName: EgrConCodigo, type: INTEGER, size: '11', required: false }
    egr_valor: { phpName: EgrValor, type: DOUBLE, required: false }
    egr_fecha: { phpName: EgrFecha, type: DATE, required: false }
    egr_fecha_registro: { phpName: EgrFechaRegistro, type: TIMESTAMP, required: false }
    egr_eliminado: { phpName: EgrEliminado, type: SMALLINT, size: '6', required: false }
    egr_usu_codigo: { phpName: EgrUsuCodigo, type: INTEGER, size: '11', required: false }
    egr_pro_codigo: { phpName: EgrProCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_11: [egr_usu_codigo], FK_reference_12: [egr_pro_codigo], FK_reference_13: [egr_con_codigo] }
  ejecutorproyecto:
    _attributes: { phpName: Ejecutorproyecto }
    eje_pro_codigo: { phpName: EjeProCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    eje_pro_nombre: { phpName: EjeProNombre, type: VARCHAR, size: '100', required: false }
  estadoproducto:
    _attributes: { phpName: Estadoproducto }
    est_prod_codigo: { phpName: EstProdCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    est_prod_nombre: { phpName: EstProdNombre, type: VARCHAR, size: '30', required: false }
  estadoproyecto:
    _attributes: { phpName: Estadoproyecto }
    est_pro_codigo: { phpName: EstProCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    est_pro_nombre: { phpName: EstProNombre, type: VARCHAR, size: '30', required: false }
  ingreso:
    _attributes: { phpName: Ingreso }
    ing_codigo: { phpName: IngCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    ing_concepto: { phpName: IngConcepto, type: VARCHAR, size: '500', required: false }
    ing_valor: { phpName: IngValor, type: DOUBLE, required: false }
    ing_fecha: { phpName: IngFecha, type: DATE, required: false }
    ing_fecha_registro: { phpName: IngFechaRegistro, type: TIMESTAMP, required: false }
    ing_eliminado: { phpName: IngEliminado, type: SMALLINT, size: '6', required: false }
    ing_usu_codigo: { phpName: IngUsuCodigo, type: INTEGER, size: '11', required: false }
    ing_pro_codigo: { phpName: IngProCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_11: [ing_usu_codigo], FK_reference_12: [ing_pro_codigo] }
  organizacion:
    _attributes: { phpName: Organizacion }
    org_codigo: { phpName: OrgCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    org_nombre_completo: { phpName: OrgNombreCompleto, type: VARCHAR, size: '200', required: false }
    org_nombre_corto: { phpName: OrgNombreCorto, type: VARCHAR, size: '200', required: false }
    org_nit: { phpName: OrgNit, type: VARCHAR, size: '100', required: false }
    org_direccion: { phpName: OrgDireccion, type: VARCHAR, size: '200', required: false }
    org_correo: { phpName: OrgCorreo, type: VARCHAR, size: '200', required: false }
    org_nombre_contacto: { phpName: OrgNombreContacto, type: VARCHAR, size: '200', required: false }
    org_telefono: { phpName: OrgTelefono, type: VARCHAR, size: '100', required: false }
    org_fecha_registro: { phpName: OrgFechaRegistro, type: TIMESTAMP, required: false }
    org_eliminado: { phpName: OrgEliminado, type: SMALLINT, size: '6', required: false }
    org_tip_codigo: { phpName: OrgTipCodigo, type: INTEGER, size: '11', required: false }
    org_usu_codigo: { phpName: OrgUsuCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_8: [org_tip_codigo], FK_reference_15: [org_usu_codigo] }
  organizacionproyecto:
    _attributes: { phpName: Organizacionproyecto }
    orpy_codigo: { phpName: OrpyCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    orpy_org_codigo: { phpName: OrpyOrgCodigo, type: INTEGER, size: '11', required: false }
    orpy_pro_codigo: { phpName: OrpyProCodigo, type: INTEGER, size: '11', required: false }
    orpy_usu_codigo: { phpName: OrpyUsuCodigo, type: INTEGER, size: '11', required: false }
    orpy_fecha_registro: { phpName: OrpyFechaRegistro, type: TIMESTAMP, required: false }
    _indexes: { FK_reference_1: [orpy_org_codigo], FK_reference_2: [orpy_pro_codigo], FK_reference_3: [orpy_usu_codigo] }
  participante:
    _attributes: { phpName: Participante }
    par_codigo: { phpName: ParCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    par_pers_codigo: { phpName: ParPersCodigo, type: INTEGER, size: '11', required: false }
    par_pro_codigo: { phpName: ParProCodigo, type: INTEGER, size: '11', required: false }
    par_usu_codigo: { phpName: ParUsuCodigo, type: INTEGER, size: '11', required: false }
    par_fecha_registro: { phpName: ParFechaRegistro, type: TIMESTAMP, required: false }
    _indexes: { FK_reference_1: [par_pers_codigo], FK_reference_2: [par_pro_codigo], FK_reference_3: [par_usu_codigo] }
  perfil:
    _attributes: { phpName: Perfil }
    per_codigo: { phpName: PerCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    per_nombre: { phpName: PerNombre, type: VARCHAR, size: '30', required: false }
  persona:
    _attributes: { phpName: Persona }
    pers_codigo: { phpName: PersCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    pers_nombres: { phpName: PersNombres, type: VARCHAR, size: '200', required: false }
    pers_apellidos: { phpName: PersApellidos, type: VARCHAR, size: '200', required: false }
    pers_numero_identificacion: { phpName: PersNumeroIdentificacion, type: VARCHAR, size: '200', required: false }
    pers_cargo: { phpName: PersCargo, type: VARCHAR, size: '200', required: false }
    pers_correo: { phpName: PersCorreo, type: VARCHAR, size: '100', required: false }
    pers_telefono: { phpName: PersTelefono, type: VARCHAR, size: '100', required: false }
    pers_celular: { phpName: PersCelular, type: VARCHAR, size: '100', required: false }
    pers_fecha_registro: { phpName: PersFechaRegistro, type: TIMESTAMP, required: false }
    pers_eliminado: { phpName: PersEliminado, type: SMALLINT, size: '6', required: false }
    pers_usu_codigo: { phpName: PersUsuCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_13: [pers_usu_codigo] }
  producto:
    _attributes: { phpName: Producto }
    prod_codigo: { phpName: ProdCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    prod_nombre: { phpName: ProdNombre, type: VARCHAR, size: '300', required: false }
    prod_fecha_entrega: { phpName: ProdFechaEntrega, type: DATE, required: false }
    prod_documento_url: { phpName: ProdDocumentoUrl, type: VARCHAR, size: '300', required: false }
    prod_fecha_registro: { phpName: ProdFechaRegistro, type: TIMESTAMP, required: false }
    prod_eliminado: { phpName: ProdEliminado, type: SMALLINT, size: '6', required: false }
    prod_pro_codigo: { phpName: ProdProCodigo, type: INTEGER, size: '11', required: false }
    prod_usu_codigo: { phpName: ProdUsuCodigo, type: INTEGER, size: '11', required: false }
    prod_est_codigo: { phpName: ProdEstCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_1: [prod_pro_codigo], FK_reference_2: [prod_usu_codigo], FK_reference_3: [prod_est_codigo] }
  proyecto:
    _attributes: { phpName: Proyecto }
    pro_codigo: { phpName: ProCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    pro_codigo_contable: { phpName: ProCodigoContable, type: VARCHAR, size: '200', required: false }
    pro_nombre: { phpName: ProNombre, type: VARCHAR, size: '500', required: false }
    pro_descripcion: { phpName: ProDescripcion, type: VARCHAR, size: '2000', required: false }
    pro_valor: { phpName: ProValor, type: DOUBLE, required: false }
    pro_acumulado_ingresos: { phpName: ProAcumuladoIngresos, type: DOUBLE, required: false }
    pro_acumulado_egresos: { phpName: ProAcumuladoEgresos, type: DOUBLE, required: false }
    pro_fecha_inicio: { phpName: ProFechaInicio, type: DATE, required: false }
    pro_fecha_fin: { phpName: ProFechaFin, type: DATE, required: false }
    pro_observaciones: { phpName: ProObservaciones, type: VARCHAR, size: '2000', required: false }
    pro_presupuesto_url: { phpName: ProPresupuestoUrl, type: VARCHAR, size: '300', required: false }
    pro_pers_codigo: { phpName: ProPersCodigo, type: INTEGER, size: '11', required: false }
    pro_est_codigo: { phpName: ProEstCodigo, type: INTEGER, size: '11', required: false }
    pro_fecha_registro: { phpName: ProFechaRegistro, type: TIMESTAMP, required: false }
    pro_eje_codigo: { phpName: ProEjeCodigo, type: INTEGER, size: '11', required: false }
    pro_tipp_codigo: { phpName: ProTippCodigo, type: INTEGER, size: '11', required: false }
    pro_otro_tipo: { phpName: ProOtroTipo, type: VARCHAR, size: '200', required: false }
    pro_eliminado: { phpName: ProEliminado, type: SMALLINT, size: '6', required: false }
    pro_usu_codigo: { phpName: ProUsuCodigo, type: INTEGER, size: '11', required: false }
    _indexes: { FK_reference_1: [pro_pers_codigo], FK_reference_2: [pro_est_codigo], FK_reference_3: [pro_usu_codigo], FK_reference_4: [pro_eje_codigo], FK_reference_5: [pro_tipp_codigo] }
  tipodocumento:
    _attributes: { phpName: Tipodocumento }
    tipd_codigo: { phpName: TipdCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    tipd_nombre: { phpName: TipdNombre, type: VARCHAR, size: '30', required: false }
  tipoorganizacion:
    _attributes: { phpName: Tipoorganizacion }
    tipo_codigo: { phpName: TipoCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    tipo_nombre: { phpName: TipoNombre, type: VARCHAR, size: '30', required: false }
  tipoproyecto:
    _attributes: { phpName: Tipoproyecto }
    tipp_codigo: { phpName: TippCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    tipp_nombre: { phpName: TippNombre, type: VARCHAR, size: '30', required: false }
  usuario:
    _attributes: { phpName: Usuario }
    usu_codigo: { phpName: UsuCodigo, type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    usu_per_codigo: { phpName: UsuPerCodigo, type: INTEGER, size: '11', required: false }
    usu_login: { phpName: UsuLogin, type: VARCHAR, size: '200', required: false }
    usu_contrasena: { phpName: UsuContrasena, type: VARCHAR, size: '200', required: false }
    usu_habilitado: { phpName: UsuHabilitado, type: SMALLINT, size: '6', required: false }
    usu_pers_codigo: { phpName: UsuPersCodigo, type: INTEGER, size: '11', required: false }
    usu_fecha_registro: { phpName: UsuFechaRegistro, type: TIMESTAMP, required: false }
    _indexes: { FK_reference_4: [usu_per_codigo], FK_reference_5: [usu_pers_codigo] }
